[package]
name = "lvm"
version = "1.0.0"
edition = "2024"

[dependencies]
mcs = { path = "../mcs" }
anyhow = { version ="1", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
