[package]
name = "mcs"
version = "1.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1", default-features = false }
syn = { version = "2", default-features = false }
